### ISSUE TITLE
8 test failures on s390x

### ISSUE THREAD

**Issue by rathann** [ccpem/mrcfile#35]
mrcfile version 1.3.0 test suite is showing 8 test failures when executed on Fedora rawhide s390x arch:
```
$ python3 -m unittest tests
..............................FF.............................................................................................................................FF..........................................................................................................................................................................................................................................................................FF.................................................................................................................FF...................................................................................../builddir/build/BUILD/mrcfile-1.3.0/tests/test_utils.py:139: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  utils.mode_from_dtype(np.dtype(np.bool))
...................................................................................
======================================================================
FAIL: test_extended_header_from_FEI1_file (tests.test_bzip2mrcfile.Bzip2MrcFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 177, in test_extended_header_from_FEI1_file
    assert ext[0]['Metadata size'] == 768
AssertionError
======================================================================
FAIL: test_extended_header_from_FEI2_file (tests.test_bzip2mrcfile.Bzip2MrcFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 193, in test_extended_header_from_FEI2_file
    assert ext[0]['Metadata size'] == 888
AssertionError
======================================================================
FAIL: test_extended_header_from_FEI1_file (tests.test_gzipmrcfile.GzipMrcFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 177, in test_extended_header_from_FEI1_file
    assert ext[0]['Metadata size'] == 768
AssertionError
======================================================================
FAIL: test_extended_header_from_FEI2_file (tests.test_gzipmrcfile.GzipMrcFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 193, in test_extended_header_from_FEI2_file
    assert ext[0]['Metadata size'] == 888
AssertionError
======================================================================
FAIL: test_extended_header_from_FEI1_file (tests.test_mrcfile.MrcFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 177, in test_extended_header_from_FEI1_file
    assert ext[0]['Metadata size'] == 768
AssertionError
======================================================================
FAIL: test_extended_header_from_FEI2_file (tests.test_mrcfile.MrcFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 193, in test_extended_header_from_FEI2_file
    assert ext[0]['Metadata size'] == 888
AssertionError
======================================================================
FAIL: test_extended_header_from_FEI1_file (tests.test_mrcmemmap.MrcMemmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 177, in test_extended_header_from_FEI1_file
    assert ext[0]['Metadata size'] == 768
AssertionError
======================================================================
FAIL: test_extended_header_from_FEI2_file (tests.test_mrcmemmap.MrcMemmapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mrcfile-1.3.0/tests/test_mrcfile.py", line 193, in test_extended_header_from_FEI2_file
    assert ext[0]['Metadata size'] == 888
AssertionError
----------------------------------------------------------------------
Ran 710 tests in 11.009s
FAILED (failures=8)
```

**Comment by rathann** [comment]
@mtasaka do you think you could lend a hand here?

**Comment by colinpalmer** [comment]
Thanks for reporting. This problem was actually anticipated ([see comment here](https://github.com/ccpem/mrcfile/blob/7b3238998d9279d55ee962961184530847811f8e/mrcfile/dtypes.py#L97-L100)) but I was never able to test mrcfile on genuine big-endian hardware so it's very useful to see the results!

I'll change the code so it uses the same endianness for the FEI extended header as it does for the rest of the file. In the meantime, if you're not intending to use the FEI extended headers in your code, you can safely ignore these test failures. The fact all the rest of the tests passed means mrcfile is generally behaving properly on your system and there aren't any other endianness problems. Apart from these failing tests, nothing in mrcfile actually uses this "Metadata size" field.

**Comment by rathann** [comment]
You're welcome! Fedora is built on s390x, so we're testing everything on big-endian regularly. I'd be happy to test any patches.
