### ISSUE TITLE
Test failures with Python 3.11

### ISSUE THREAD

**Issue by mgorny** [ccpem/mrcfile#41]
There's a bunch of test failures with Python 3.11.0b3, apparently due to exception messages having changed:

```pytb
======================================================================
FAIL: test_setting_data_attribute_raises_exception (tests.test_bzip2mrcfile.Bzip2MrcFileTest.test_setting_data_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'data' of 'Bzip2MrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 102, in test_setting_data_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'data' of 'Bzip2MrcFile' object has no setter"

======================================================================
FAIL: test_setting_extended_header_attribute_raises_exception (tests.test_bzip2mrcfile.Bzip2MrcFileTest.test_setting_extended_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'extended_header' of 'Bzip2MrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 98, in test_setting_extended_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'extended_header' of 'Bzip2MrcFile' object has no setter"

======================================================================
FAIL: test_setting_header_attribute_raises_exception (tests.test_bzip2mrcfile.Bzip2MrcFileTest.test_setting_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'header' of 'Bzip2MrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 94, in test_setting_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'header' of 'Bzip2MrcFile' object has no setter"

======================================================================
FAIL: test_setting_data_attribute_raises_exception (tests.test_gzipmrcfile.GzipMrcFileTest.test_setting_data_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'data' of 'GzipMrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 102, in test_setting_data_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'data' of 'GzipMrcFile' object has no setter"

======================================================================
FAIL: test_setting_extended_header_attribute_raises_exception (tests.test_gzipmrcfile.GzipMrcFileTest.test_setting_extended_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'extended_header' of 'GzipMrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 98, in test_setting_extended_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'extended_header' of 'GzipMrcFile' object has no setter"

======================================================================
FAIL: test_setting_header_attribute_raises_exception (tests.test_gzipmrcfile.GzipMrcFileTest.test_setting_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'header' of 'GzipMrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 94, in test_setting_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'header' of 'GzipMrcFile' object has no setter"

======================================================================
FAIL: test_setting_data_attribute_raises_exception (tests.test_mrcobject.MrcObjectTest.test_setting_data_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'data' of 'MrcObject' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 102, in test_setting_data_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'data' of 'MrcObject' object has no setter"

======================================================================
FAIL: test_setting_extended_header_attribute_raises_exception (tests.test_mrcobject.MrcObjectTest.test_setting_extended_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'extended_header' of 'MrcObject' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 98, in test_setting_extended_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'extended_header' of 'MrcObject' object has no setter"

======================================================================
FAIL: test_setting_header_attribute_raises_exception (tests.test_mrcobject.MrcObjectTest.test_setting_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'header' of 'MrcObject' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 94, in test_setting_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'header' of 'MrcObject' object has no setter"

======================================================================
FAIL: test_setting_data_attribute_raises_exception (tests.test_mrcinterpreter.MrcInterpreterTest.test_setting_data_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'data' of 'MrcInterpreter' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 102, in test_setting_data_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'data' of 'MrcInterpreter' object has no setter"

======================================================================
FAIL: test_setting_extended_header_attribute_raises_exception (tests.test_mrcinterpreter.MrcInterpreterTest.test_setting_extended_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'extended_header' of 'MrcInterpreter' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 98, in test_setting_extended_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'extended_header' of 'MrcInterpreter' object has no setter"

======================================================================
FAIL: test_setting_header_attribute_raises_exception (tests.test_mrcinterpreter.MrcInterpreterTest.test_setting_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'header' of 'MrcInterpreter' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 94, in test_setting_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'header' of 'MrcInterpreter' object has no setter"

======================================================================
FAIL: test_setting_data_attribute_raises_exception (tests.test_mrcfile.MrcFileTest.test_setting_data_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'data' of 'MrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 102, in test_setting_data_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'data' of 'MrcFile' object has no setter"

======================================================================
FAIL: test_setting_extended_header_attribute_raises_exception (tests.test_mrcfile.MrcFileTest.test_setting_extended_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'extended_header' of 'MrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 98, in test_setting_extended_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'extended_header' of 'MrcFile' object has no setter"

======================================================================
FAIL: test_setting_header_attribute_raises_exception (tests.test_mrcfile.MrcFileTest.test_setting_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'header' of 'MrcFile' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 94, in test_setting_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'header' of 'MrcFile' object has no setter"

======================================================================
FAIL: test_setting_data_attribute_raises_exception (tests.test_mrcmemmap.MrcMemmapTest.test_setting_data_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'data' of 'MrcMemmap' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 102, in test_setting_data_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'data' of 'MrcMemmap' object has no setter"

======================================================================
FAIL: test_setting_extended_header_attribute_raises_exception (tests.test_mrcmemmap.MrcMemmapTest.test_setting_extended_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'extended_header' of 'MrcMemmap' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 98, in test_setting_extended_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'extended_header' of 'MrcMemmap' object has no setter"

======================================================================
FAIL: test_setting_header_attribute_raises_exception (tests.test_mrcmemmap.MrcMemmapTest.test_setting_header_attribute_raises_exception)
----------------------------------------------------------------------
AttributeError: property 'header' of 'MrcMemmap' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/mrcfile/tests/test_mrcobject.py", line 94, in test_setting_header_attribute_raises_exception
    with self.assertRaisesRegex(AttributeError, "can't set attribute"):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: "can't set attribute" does not match "property 'header' of 'MrcMemmap' object has no setter"

----------------------------------------------------------------------
Ran 730 tests in 14.119s

FAILED (failures=18)
```

**Comment by colinpalmer** [comment]
Thanks for reporting this. I wasn't planning to add Python 3.11 support until it was released, but since it seems to work with only a few minor test updates I've gone ahead and fixed this now. The tests should pass in Python 3.11 if you use the latest code from GitHub now and the changes will be included in the next PyPI release.

**Comment by mgorny** [comment]
Thanks!
