### ISSUE TITLE
OverflowError: Python integer out of bounds for int32,  when reading large file

### ISSUE THREAD

**Issue by procyontao** [ccpem/mrcfile#63]
I am using mrcfile version 1.5.0 to open a tomogram file with 1022x1440x500 pixels and it gave me the following error
```python
>>> import mrcfile
>>> with mrcfile.open("ts_621_bin4_rec_trimed.mrc", permissive=True) as mrc:
...     data = mrc.data
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cii/anaconda3/envs/cryocat/lib/python3.9/site-packages/mrcfile/load_functions.py", line 139, in open
    return NewMrc(name, mode=mode, permissive=permissive,
  File "/home/cii/anaconda3/envs/cryocat/lib/python3.9/site-packages/mrcfile/mrcfile.py", line 115, in __init__
    self._read(header_only)
  File "/home/cii/anaconda3/envs/cryocat/lib/python3.9/site-packages/mrcfile/mrcfile.py", line 131, in _read
    super(MrcFile, self)._read(header_only)
  File "/home/cii/anaconda3/envs/cryocat/lib/python3.9/site-packages/mrcfile/mrcinterpreter.py", line 173, in _read
    self._read_data()
  File "/home/cii/anaconda3/envs/cryocat/lib/python3.9/site-packages/mrcfile/mrcfile.py", line 137, in _read_data
    remaining_file_size = file_size - header_size
OverflowError: Python integer 2943425024 out of bounds for int32

``` 

This is an out of bound problem of np.int32 type and I fixed it by replacing header_size with int(header_size)
https://github.com/ccpem/mrcfile/blob/28d72bf365079d29db4cc84c82ad42b06e540262/mrcfile/mrcfile.py#L137

**Comment by colinpalmer** [comment]
This should be fixed now, in mrcfile 1.5.3. If you come across any other problems opening large files please do open a new issue.
